version: '3.3'
services:
    poste:
        image: analogic/poste.io
        container_name: poste
        restart: always
        hostname: mail.softwec.dev
        networks:
           - network_poste
        environment:
           - HTTPS=ON
        ports:
           - "25:25"
           - "80:80"
           - "443:443"
           - "110:110"
           - "143:143"
           - "465:465"
           - "587:587"
           - "993:993"
           - "995:995"
           - "4190:4190"
        volumes:
           - $PATH_MAIL_LOCAL:$PATH_MAIL_CONTAINER

networks:
    network_poste:
         driver: bridge