version: '3.3'
services:
    poste:
        image: analogic/poste.io
        container_name: poste
        restart: always
        networks:
           - network_poste
        ports:
           - "25:25"
           - "8000:80"
           - "4455:443"
           - "110:110"
           - "143:143"
           - "465:465"
           - "587:587"
           - "993:993"
           - "995:995"
           - "4190:4190"
        environment:
           - HTTPS=ON
        volumes:
           - $PATH_MAIL_LOCAL:$PATH_MAIL_CONTAINER
networks:
     network_poste:
       driver: bridge