version: '3.3'
services:
    poste:
        image: analogic/poste.io
        container_name: poste
        restart: always
        network_mode: host
        environment:
           - HTTPS=ON
        volumes:
           - $PATH_MAIL_LOCAL:$PATH_MAIL_CONTAINER